### ISSUE TITLE
Feature request: View "entered by" data as part of a member's normal record view.

### ISSUE THREAD

**Issue by myself248** [elplatt/seltzer#357]
Currently, Seltzer sends out an email when a new contact is created, and at the bottom of the email, it shows who did the creation. Is that data stored anywhere? If so, could it be displayed as part of a member's contact view?

**Comment by chris18890** [comment]
no, the data isn't stored anywhere, but it wouldn't be to difficult to add a timestamp column into the table; thoughts on this (form a modifying the DB perspective) @elplatt?

**Comment by ramgarden** [comment]
I was also thinking about adding a "paper trail" auditing module that has its own table that would be added to the DB instead of changing existing schema.  It would track who added a new contact, added a payment, deleted a member, and basically every change made.  I'm not sure how well a module can be created that would "know" when all of these things happened though.  So it might need to be added to the core code/modules?  I do like the idea of adding a separate AUDIT_TRAIL or PAPER_TRAIL table that has a timestamp of when the action happened, who did the action, and what the action was.  Thoughts?

**Comment by chris18890** [comment]
Interesting idea! I know issue #13 was opened for that idea but not sure if anything was actioned from it
